### ISSUE TITLE
Parsable output doesnt provide a network interface usage percentage

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#102]
It can be calculated from -P NET, but currently I see no way to get the percentage from parsable output as it is presented in the upper pane within the ncurses GUI.

**Comment by Atoptool** [comment]
The parsable output is meant to provide the raw counters, leaving all the processing and calculations to the script that reads these counters. None of the busy percentages (cpu, disk, network, etc) as shown by atop (interactive) or atopsar are provided via the parsable output, because they can be calculated from the given counters.
