### ISSUE TITLE
atopsar: get statistics for specific pid

### ISSUE THREAD

**Issue by gsmol** [Atoptool/atop#105]
Thank you for all your work on this handy tool!

Suppose I have an atop log with 1 minute interval and I would like to get some specific metrics for specific pid. Something like that:
```
TIME          RDDSK     WRDSK    CPU     PID 
10:00:00      234.3G    1.6G     1565%   1115
10:01:00      348.0G      0K     2166%   1115
10:02:00      348.5G      0K     2168%   1115
10:03:00      123.3G    4.8G    10429%   1115
10:04:00      79.6G     4.8G    11896%   1115
10:05:00      70.4G     5.7G    11914%   1115
10:06:00      82.8G     5.4G    11922%   1115
10:07:00      103.7G    5.4G    11909%   1115
``` 
Is it possible with atopsar ?

**Comment by Atoptool** [comment]
Atopsar is meant to show system level reports, rather than process level reports.
The report example of a specific process could be generated by scripting the parseable output as produced with the -P flag.
Another possibility is to run "atop -r | egrep '1115|^ATOP' " (where 1115 is the PID to be searched) which shows all lines related to process 1115 and all header lines (^ATOP) from which the timestamp can be retrieved. A small script can generate a report from that information.
