### ISSUE TITLE
Nice problem

### ISSUE THREAD

**Issue by IgorOhrimenko** [Atoptool/atop#128]
The default debian service does not allow to set Nice= at systemd.service. When Service starting `/usr/share/atop/atop.daily` Nice set right, but last command `exec $BINPATH/atop -a -R -w $LOGPATH/atop_$CURDAY $INTERVAL > $LOGPATH/daily.log 2>&1` rewrite Nice.
I am found https://github.com/Atoptool/atop/blob/master/atop.service and replaced default debian service, but Nice does not work, after that I added `ExecStartPost=/bin/sh -c '/usr/bin/renice -n +19 -p $(/bin/pidof atop)'` at the service file and now it is work.

The way I have found seems ugly to me. How did you solve the priority management problem?

**Comment by Atoptool** [comment]
Atop tries to decrement its nice value by 20 to raise its own priority, because it is important that atop continues monitoring the system even when the CPUs are heavily utilized. This decrement only succeeds when atop runs with the proper capability (usually when started with root privileges). Can you explain why you want to start atop with a very low priority?

**Comment by Atoptool** [comment]
Please reopen this issue when more information is available.
