### ISSUE TITLE
DSK reports busy 93% though avio only 0.14 MS

### ISSUE THREAD

**Issue by ak370** [Atoptool/atop#137]
10sec average:
![image](https://user-images.githubusercontent.com/16243486/98842656-cca87b80-2441-11eb-9e42-e3820f82880a.png)

Should it not report 93% busy only when avio is closer to 930ms?

Related to https://github.com/Atoptool/atop/issues/47 ?

Using
atop 2.4.0-3
kernel 5.4.0-52-generic
Ubuntu 20.04.1 LTS
Software RAID1 on Dell HBA330 with 2x SSDs - Samsung MZILT1T9HAJQ0D3
PowerEdge R740xd

Thanks

**Comment by Atoptool** [comment]
As described in the manual page of atop, the 'avio' value shows the average number of milliseconds *per request*. In the given example output, more than 68000 requests ('read' + 'write') are issued in 10 seconds, which means about 6800 per second. With an average request time of 0.14 ms, the disk could be busy for (6800 * 0.14) 952 ms in one second. That might mean 95% busy, however since I/O requests can be done in overlap the value of 93% busy is very plausible.

**Comment by ak370** [comment]
Thank you. I get 93% busy but that is only average 24.7MB/s which on SDD disks is pretty little. During benchmarks I can get speeds of around 750MB/s.. Of course there might be some discrepancies but not that that level. I understand atop looks at number of I/Os and multiplies by average latency. This is database so lots of small multithreaded writes, I guess overlap/multithreading is much higher and wonder how to calculate it more accurately as this utilisation figure is I suspect incorrect, again due to calculating latency of multiple IOs that likely are happening in parallel rather than in serial way?

i.e. with iostat I get some few hundred percent utilisation% which is probably is also questionable way of scale beyond 100%?

**Comment by ak370** [comment]
Or is it due to some queueing mechanism the remaining 1% of available utilisation becomes much lower latency or could it be due to some speed scaling? Would appreciate any reference.
