### ISSUE TITLE
Hide "SWP" row when swap is disabled.

### ISSUE THREAD

**Issue by Mike-Benoit** [Atoptool/atop#18]
When a swap partition doesn't exist, atop shows a "SWP" row with 0.0M total and 0.0M free, and highlights it in red, I'm assuming because there is 0.0M free. If swap total is 0.0M, perhaps just hide this row completely?

**Comment by Atoptool** [comment]
When no swap space is used, the total and free swap is not coloured red (at least, not with recent versions of atop). I just intended to add some new counters to the SWP line because the MEM line is already somewhat 'overloaded' with memory-related counters. In that case it is not desirable any more to hide the SWP line entirely.
