### ISSUE TITLE
The Parsable API should be Stable (even across minor version changes: i.e: 2.5 -> 2.7)

### ISSUE THREAD

**Issue by gleventhal** [Atoptool/atop#200]
I wrote a tool that Parses the Parsable API and and blocked from updating atop from 2.5.0 to 2.7.1 because there are new fields in existing labels (like PRG, PRC).  I would have expected these to be stable APIs.

Perhaps you can add a fixed number of fields for each label, and then use a place holder .  That way the number of fields doesnt change, and we can write software that uses atop.  There are already not many interfaces for writing tools to leverage atop's data, and breaking the Parasable API makes it very difficult to maintain our tool.  

That said, I think atop is the best tool, and I've honestly probably gotten 500-1000 people to start using it from my recommendations.  Thanks you for making it!

**Comment by Atoptool** [comment]
Thanks!

The parsable API is meant to offer a stable interface for tools that want to post-process the measured data. Whenever a new counter is introduced for the interactive interface, that counter will also be added in the corresponding line of the parsable API. This will always be done at the end of the line, not to break the order of the fields for existing parsing tools. Likewise, when a counter is not relevant any more, it will be replaced by a place holder. Since new counters are often introduced in minor releases, also counters might be added to the parsable API in minor releases.
In general, parsing tools take the required field numbers from the actual line of parsable output without being affected by the total number of fields offered (even if more fields have been added). Is that not possible in your tooling?

**Comment by Atoptool** [comment]
Please write tools that use parsable data in such a way that additional counters (at the end of the line) do not harm.
