### ISSUE TITLE
-R option by default causes performance degradation

### ISSUE THREAD

**Issue by jynus** [Atoptool/atop#27]
The -R option should not be enabled by default (atop.daily). In previous versions, it ran without -R. Degradation with high CPU usage has been observed on production hosts with lots of memory and processes, so I don't think it should be set by default.

For context and proof, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896767 and https://phabricator.wikimedia.org/T192551

**Comment by Zugschlus** [comment]
maintainer of the Debian package here. I do not agree with the bug reporter since he is running a very big host under high load. It is clear that such hosts need tweaking. Running atop with -R is ok for the vast majority of systems out there, especially the ones with the less experienced administrators.

My suggestion would be to make that configurable, with -R being the easily changeable default. Unfortunately, this currently means to modify a file that comes from the distribution.

**Comment by Atoptool** [comment]
I will look for a way to make this option configurable in a file that doesn't come with the distribution.

Notice that the amount of RAM memory is not causing the CPU consumption, but the number of processes on the system is. For every process, atop has to read the /proc/pid/smaps file in case that the R option is active. Since atop itself is a single-threaded process, it should at most occupy one of the cores.

**Comment by Zugschlus** [comment]
The suggested patch #28  does indeed make this option configurable in a file that doesn't come with the distribution.

**Comment by Atoptool** [comment]
By implementing the suggested patch (and some additional modifications), you can create the configuration file /etc/default/atop (will not be overruled by the distribution). Add the line containing

LOGOPTS=

to overrule the -R option.

**Comment by dwinrick-lever** [comment]
@Zugschlus 
Just wanted to note that this had a pretty severe performance impact when installed on a machine that hosted a database server. 

This was *especially* problematic when that machine was promoted to primary in the cluster, and started taking down that DB shard every day at 5PM PST...

The machine would normally be under petty low load, but at 00 UTC we'd see it act as if all IO was taking several seconds.

I think the core problem is that installing the package adds a cron.

**Comment by Zugschlus** [comment]
On a systemd system, that "cron" just restarts atop. If you don't like atop's default configuration, change it.

**Comment by dwinrick-lever** [comment]
What you're saying is interesting, which is that it's okay to ship default configuration that can have large performance implications without a warning. I imagine that most folks will install atop and use it like htop, or top, but instead they get a cron with a pretty big performance penalty. Would you be open to removing the cron or having it as a separate package/installation instructions?

**Comment by Atoptool** [comment]
In atop 2.6 the flag -R has already been removed as default option.
Am I right that this discussion is specifically related to the Debian atop package?

**Comment by Zugschlus** [comment]
I missed the upstream change, my apologies. Was that done because you believe that was the right thing to do or just because the complaints were so loud?

**Comment by Atoptool** [comment]
There were several complaints about systems that got delayed every 10 minutes, especially when a huge number of processes was involved. It was also the reason for people to deinstall atop again, not being aware that the issue could be solved by removing the -R flag. Therefore I believed it was the right thing to remove the -R flag as default option.

**Comment by Zugschlus** [comment]
Debian will go along with that decision then. Thanks for the clarification.
