### ISSUE TITLE
How to get the full username (EUID) of a process?

### ISSUE THREAD

**Issue by martinvonwittich** [Atoptool/atop#309]
I'm using `atop` interactively in the `g` (generic) view sorted by `D` (disk activity) to identify several users who have caused a high system load. Unfortunately, the usernames in the EUID column are limited to 8 characters, which makes some usernames ambiguous. Is it possible to show the actual user ID (so I can map the ID -> username myself), or to increase the column width?

**Comment by Atoptool** [comment]
With the -I flag the translation from a UID/GID to a name will be suppressed, so all UIDs and GIDs will be shown as numbers. This can be useful to view a raw log file from another system (to avoid wrong translations using info from the local system).

Besides, when a user name or group name is longer than 8 characters it will automatically be presented as a number instead of showing a truncated name (even if the -I flag has not been used).
