### ISSUE TITLE
atop stops rotating logs

### ISSUE THREAD

**Issue by DavorSaric** [Atoptool/atop#33]
Hello,

I have encountered this on all my CentOS 7 servers over time, atop just stops rotating logs, these are the latest ones:

-rw-r--r--  1 root root 2305250 May  1 23:50 atop_20180501
-rw-r--r--  1 root root 2655114 May  2 20:00 atop_20180502
-rw-------  1 root root      66 May  2 20:23 atop.log-20180503
-rw-------  1 root root       0 Aug  1 13:30 atop.log
-rw-r--r--  1 root root  344698 Aug  1 13:30 atop_20180801

Weird is the name of the atop.log-20180503, I don't know why this one has a .log in its name while others doesn't have it and seems like the last log file had name atop.log-20180503 but it should be atop_20180503.

I have found this link so it is present on Debian Strech also https://blog.pyshonk.in/2016/11/11/atop-log-does-not-rotate-in-debian-stretch/

but CentOS 7 doesn't use invoke-rc.

Should the cron have "restart" instead of "try-restart? Like this:

0 0 * * * root /bin/systemctl restart atop.service > /dev/null 2>&1 || :

instead of this:

0 0 * * * root /bin/systemctl try-restart atop.service > /dev/null 2>&1 || :

**Comment by DavorSaric** [comment]
I use the atop from CentOS/Epel

**Comment by Atoptool** [comment]
The naming/handling of the log files and the contents of the cron file ('try-restart') is really different from the 'atoptool' implementation. Please pass this issue to the packagers of EPEL.

**Comment by joeytwiddle** [comment]
Having a similar problem here. When starting the atop service, a logfile is created with today's date, but it never changes, so that one file contains all logs for future days as well.

Here is my workaround: Run `crontab -e` and add the following:

```
0 0 * * * systemctl restart atop
```

Now atop will start a new logfile at the start of each day!

Are there any great disadvantages to this?

As for reporting to EPEL, they seem to be aware of it. ([Search](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=POST&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&bug_status=__open__&bug_status=__closed__&bug_status=CLOSED&classification=Fedora&list_id=12250155&order=Importance&product=Fedora%20EPEL&query_format=advanced&short_desc=atop%20log&short_desc_type=allwordssubstr)) The current open bugreport is [here](https://bugzilla.redhat.com/show_bug.cgi?id=1425830).
