### ISSUE TITLE
Binary log doesn't record usernames, just user IDs

### ISSUE THREAD

**Issue by callumapplsys** [Atoptool/atop#68]
When writing to the binary log with the `-w` option, then transferring that log to another machine, and reading with the `-r` option, the username IDs are looked up against the local machines users file, rather than being recorded by atop. This ends up with inconsistent results.

**Comment by jbd** [comment]
Much better problem statement. I'll close mine (https://github.com/Atoptool/atop/issues/32)

**Comment by Atoptool** [comment]
With the -I flag the translation from a UID/GID to a name will be suppressed, so all UIDs and GIDs will be shown as numbers. This can be useful to view a raw log file from another system (to avoid wrong translations using info from the local system).

Besides, when a user name or group name is longer than 8 characters it will automatically be presented as a number instead of showing a truncated name (even if the -I flag has not been used).
