### ISSUE TITLE
atop stops with buffer overflow

### ISSUE THREAD

**Issue by e-ferrari** [Atoptool/atop#79]
Hi,
i have a linux system which stops responding for several hours. No ssh-login possible, no local login. Just responding to ping.
I have on all of my linux systems atop running which logs each second. So i can investigate afterwards what was going on on that system. Unfortunately, when i jump with 'b' some seconds before system didn't respond anymore, and then approach with 't', i get a buffer overflow.
System is SLES 10 SP4, atop is atop-1.27.3-2.1. Is it possible that the logfile is corrupt and this causes the buffer overflow ? Is there a way to "fix" that file ?
I tried to open the file with more recent versions of atop but i got:
ha-idg-1:~ # atop -r atop_20190917
raw file atop_20190917 has incompatible format
(created by version 1.27 - current version 2.2)
trying to activate atop-1.27....
activation of atop-1.27 failed!

Does each version have its own format ? Which version could be helpful ?
Or is there a way to convert the logfile into a more recent format ?
Thanks.

Bernd

**Comment by e-ferrari** [comment]
Oh, i forgot: I did a "strace" on atop but don't see the reason for the buffer overflow.
But i'm not an expert in interpreting strace.
I can provide the strace-log and also the atop-log via Seafile if necessary.
Bernd

**Comment by Atoptool** [comment]
Hi, this sounds as if the corruption of the logfile might be caused by the system hang. When the system stops at the moment that atop is writing to the logfile (which was done in several portions with the version of atop), the logfile will certainly be corrupted.
Some versions of atop have introduced new formats of the logfile. The logfile formats of atop version 2.0 and higher can be converted into newer formats with the atop covert program.
Anyhow, you are using a very old version of atop. Is it possible to install a newer version (not for this specific logfile, but to avoid this situation in the future)?
